### ISSUE TITLE
Filtered validation files

### ISSUE THREAD

**Issue by amanchadha** [v-iashin/MDVC#1]
>>> "As we mentioned in the paper, we didn't have access to the full dataset as ActivityNet Captions is distributed as the list of links to YouTube video. Consequently, many videos (~8.8 %) were no longer available at the time when we were downloading the dataset. In addition, some videos didn't have any speech. We filtered out such videos from the validation files and reported the results as no missings in the paper. Please create an issue if you would like us to share these filtered validation files."

Can you please share the filtered validation files? Thanks!

**Comment by v-iashin** [comment]
Hi, sure! Please check out the latest commit.
