### ISSUE TITLE
ASR

### ISSUE THREAD

**Issue by niu1970** [v-iashin/MDVC#14]
Hello! I want to ask what API is used to obtain .srt subtitles?

**Comment by v-iashin** [comment]
See https://github.com/v-iashin/MDVC/issues/11#issuecomment-644612209
Please check this issue it has some advice which might be related to your question. Here is the gist:

> Google ASR system used on YouTube has a proprietary license. We don't have access to it and merely used its output downloaded for each video from the service.

> If your custom video is not on YouTube, start by looking for a solution that will do the ASR for a video. In a case, if your videos are from YouTube, try to obtain the CC for the video (how? I can only give you a hint: "Google is your friend" 😉).

**Comment by duola1970** [comment]
Hello! Then I would like to ask, how did you get your .srt subtitle file?
