### ISSUE TITLE
ASR

### ISSUE THREAD

**Issue by niu1970** [v-iashin/MDVC#15]
Hello! Then I would like to ask, how did you get your .srt subtitle file?Is the .srt subtitle file downloaded directly on YouTube, or is it obtained by calling Google’s API?

**Comment by v-iashin** [comment]
Hi, I can say that we obtained `.srt` for each available video and it wasn't through the Google API because the access to it is limited.

**Comment by niu1970** [comment]
Then why did you only get some .srt files of the video? If a video has audio, shouldn't it also be able to get its subtitle file?And where did you get your subtitle files? Is it convenient to post to get the URL?

**Comment by v-iashin** [comment]
I used Google2SRT
