### ISSUE TITLE
503 service unavailable: cannot open a3s.fi links

### ISSUE THREAD

**Issue by v-iashin** [v-iashin/MDVC#16]
Hi, 

Since this Monday the bucket storage that we use for storing features and models (`a3s`) is down. Usually, it takes several hours to recover but this time it is more serious, it seems. The problem is claimed to be 'temporally' but we are not sure when it will recover so for now please use this issue to let us know if you need any of the files ASAP – we will share them via other means.

Sorry for the trouble and good luck with your research!

**Comment by dhruva169** [comment]
Hi,

Can you share the pre-trained model file?

**Comment by v-iashin** [comment]
@dhruva169 
Hi, 

Sure! Here you are: [link](https://tuni-my.sharepoint.com/:u:/g/personal/vladimir_iashin_tuni_fi/EaoYdVvYwWBAtdFD6shzFsMBqhbK67YRSvDWyNoDAjgSow?e=2Lb4Oj)
`55cda5bac1cf2b7a803da24fca60898b  best_model.pt`

Sorry for the inconvenience. Let me know if you face any technical difficulties with downloading the weights.

The link will expire on the 17th of May, 2021. Therefore, avoid relying on it too much and, by default, use the links from the `README.md`.

**Comment by v-iashin** [comment]
The problem is resolved. Feel free to use this issue if you will have any trouble with the links.

**Comment by v-iashin** [comment]
The storage is down again

**Comment by v-iashin** [comment]
The problem is resolved. Feel free to use this issue if you will have any trouble with the links.
