### ISSUE TITLE
ResolvePackageNotFound Issue

### ISSUE THREAD

**Issue by sslee8778960** [v-iashin/MDVC#17]
When I try to use your yml file to create the virtual environment i have following error message.

ResolvePackageNotFound:
  - cffi==1.14.0=py37h2e261b9_0
  - msgpack-python==0.5.6=py37h6bb024c_1
  - numpy-base==1.15.4=py37hde5b4d6_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - cymem==1.31.2=py37h6bb024c_0
  - tk==8.6.8=hbc83047_0
  - libedit==3.1.20181209=hc058e9b_0
  - mkl_random==1.1.0=py37hd6b4f25_0
  - ninja==1.9.0=py37hfd86e86_0
  - python==3.7.7=hcf32534_0_cpython
  - openssl==1.1.1g=h516909a_0
  - zlib==1.2.11=h7b6447c_3
  - libtiff==4.1.0=h2733197_0
  - mkl-service==2.3.0=py37he904b0f_0
  - regex==2018.07.11=py37h14c3975_0
  - readline==8.0=h7b6447c_0
  - libpng==1.6.37=hbc83047_0
  - cytoolz==0.9.0.1=py37h14c3975_1
  - hdf5==1.10.2=hba1933b_1
  - preshed==1.0.1=py37he6710b0_0
  - sqlite==3.31.1=h62c20be_1
  - libgcc-ng==9.1.0=hdf63c60_0
  - ujson==2.0.3=py37he6710b0_0
  - xz==5.2.5=h7b6447c_0
  - openjdk==11.0.1=h516909a_1016
  - freetype==2.9.1=h8a8886c_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - h5py==2.8.0=py37h989c5e5_3
  - mkl_fft==1.0.15=py37ha843d7b_0
  - pytorch==1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - numpy==1.15.4=py37h7e9f1db_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - protobuf==3.11.4=py37h3340039_1
  - spacy==2.0.12=py37h962f231_0
  - libffi==3.2.1=hd88cf55_4
  - libprotobuf==3.11.4=h8b12597_0
  - thinc==6.10.3=py37h962f231_0
  - ncurses==6.2=he6710b0_1
  - cryptography==2.8=py37h1ba5d50_0
  - murmurhash==0.28.0=py37hf484d3e_0
  - pillow==7.1.2=py37hb39fc2d_0
  - pandas==0.24.2=py37he6710b0_0
  - jpeg==9b=h024ee3a_2
  - wrapt==1.10.11=py37h14c3975_2
  - zstd==1.3.7=h0b5b093_0
  - torchvision==0.3.0=py37_cu10.0.130_1
Can u please tell me how to handle this issue? Thank you!

**Comment by v-iashin** [comment]
Are you trying to install it on Windows?

**Comment by sslee8778960** [comment]
Yes man!

**Comment by sslee8778960** [comment]
Is there any way I could try your code on google Colab if working it on Windows is not suggested? I am new to this. Thank you very much!

**Comment by sslee8778960** [comment]
I did some research and tried to move all the failed packages into pip section. The error is resolved but i encountered new error message.

The following is my revised version:

name: mdvc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.1=py37_0
  - asn1crypto=1.3.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - chardet=3.0.4=py37_1003
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - dill=0.2.9=py37_0
  - future=0.17.1=py37_0
  - idna=2.9=py_1
  - intel-openmp=2020.0=166
  - markdown=3.2.1=py_0
  - mkl=2020.0=166
  - msgpack-numpy=0.4.4.3=py_0
  - olefile=0.46=py37_0
  - pip=20.0.2=py37_1
  - plac=0.9.6=py37_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py37_0
  - pysocks=1.7.1=py37_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - requests=2.23.0=py37_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - tensorboard=1.14.0=py37_0
  - termcolor=1.1.0=py37_1
  - toolz=0.10.0=py_0
  - tqdm=4.45.0=py_0
  - urllib3=1.25.8=py37_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py37_0
  - pip:
    - torchtext==0.3.1
    - cffi==1.14.0=py37h2e261b9_0
    - torchvision=0.3.0=py37_cu10.0.130_1
    - ninja=1.9.0=py37hfd86e86_0
    - readline=8.0=h7b6447c_0
    - zlib=1.2.11=h7b6447c_3
    - regex=2018.07.11=py37h14c3975_0
    - libtiff=4.1.0=h2733197_0
    - libffi=3.2.1=hd88cf55_4
    - zstd=1.3.7=h0b5b093_0
    - tk=8.6.8=hbc83047_0
    - libstdcxx-ng=9.1.0=hdf63c60_0
    - libedit=3.1.20181209=hc058e9b_0
    - preshed=1.0.1=py37he6710b0_0
    - cryptography=2.8=py37h1ba5d50_0
    - thinc=6.10.3=py37h962f231_0
    - ncurses=6.2=he6710b0_1
    - protobuf=3.11.4=py37h3340039_1
    - murmurhash=0.28.0=py37hf484d3e_0
    - sqlite=3.31.1=h62c20be_1
    - numpy-base=1.15.4=py37hde5b4d6_0
    - hdf5=1.10.2=hba1933b_1
    - openssl=1.1.1g=h516909a_0
    - pytorch=1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0   
    - mkl_fft=1.0.15=py37ha843d7b_0
    - pillow=7.1.2=py37hb39fc2d_0
    - wrapt=1.10.11=py37h14c3975_2
    - ujson=2.0.3=py37he6710b0_0
    - h5py=2.8.0=py37h989c5e5_3
    - msgpack-python=0.5.6=py37h6bb024c_1
    - ld_impl_linux-64=2.33.1=h53a641e_7
    - numpy=1.15.4=py37h7e9f1db_0
    - pandas=0.24.2=py37he6710b0_0
    - cymem=1.31.2=py37h6bb024c_0
    - libgcc-ng=9.1.0=hdf63c60_0
    - cytoolz=0.9.0.1=py37h14c3975_1
    - libprotobuf=3.11.4=h8b12597_0
    - jpeg=9b=h024ee3a_2
    - openjdk=11.0.1=h516909a_1016
    - mkl-service=2.3.0=py37he904b0f_0
    - spacy=2.0.12=py37h962f231_0
    - freetype=2.9.1=h8a8886c_1
    - python=3.7.7=hcf32534_0_cpython
    - libgfortran-ng=7.3.0=hdf63c60_0
    - libpng=1.6.37=hbc83047_0
    - xz=5.2.5=h7b6447c_0
    - mkl_random=1.1.0=py37hd6b4f25_0

And the following is the new error message i have encountered.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.0
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base conda



Downloading and Extracting Packages
dill-0.2.9           | 135 KB    | ############################################################################################### | 100%
msgpack-numpy-0.4.4. | 8 KB      | ############################################################################################### | 100%
olefile-0.46         | 49 KB     | ############################################################################################### | 100%
pip-20.0.2           | 1.9 MB    | ############################################################################################### | 100%
cudnn-7.3.1          | 148.7 MB  | ############################################################################################### | 100%
python-dateutil-2.8. | 220 KB    | ############################################################################################### | 100%
asn1crypto-1.3.0     | 158 KB    | ############################################################################################### | 100%
ca-certificates-2020 | 184 KB    | ############################################################################################### | 100%
pytz-2019.3          | 237 KB    | ############################################################################################### | 100%
cudatoolkit-10.0.130 | 250.0 MB  | ############################################################################################### | 100%
_libgcc_mutex-0.1    | 4 KB      | ############################################################################################### | 100%
six-1.14.0           | 23 KB     | ############################################################################################### | 100%
urllib3-1.25.8       | 170 KB    | ############################################################################################### | 100%
libblas-3.8.0        | 3.5 MB    | ############################################################################################### | 100%
requests-2.23.0      | 84 KB     | ############################################################################################### | 100%
mkl-2020.0           | 98.9 MB   | ############################################################################################### | 100%
plac-0.9.6           | 38 KB     | ############################################################################################### | 100%
werkzeug-1.0.1       | 239 KB    | ############################################################################################### | 100%
intel-openmp-2020.0  | 1.5 MB    | ############################################################################################### | 100%
pyreadline-2.1       | 146 KB    | ############################################################################################### | 100%
idna-2.9             | 52 KB     | ############################################################################################### | 100%
tensorboard-1.14.0   | 3.2 MB    | ############################################################################################### | 100%
wheel-0.34.2         | 60 KB     | ############################################################################################### | 100%
libcblas-3.8.0       | 3.5 MB    | ############################################################################################### | 100%
wincertstore-0.2     | 15 KB     | ############################################################################################### | 100%
termcolor-1.1.0      | 8 KB      | ############################################################################################### | 100%
tqdm-4.45.0          | 58 KB     | ############################################################################################### | 100%
msgpack-python-1.0.2 | 80 KB     | ############################################################################################### | 100%
liblapack-3.8.0      | 3.5 MB    | ############################################################################################### | 100%
vc-14.2              | 12 KB     | ############################################################################################### | 100%
vs2015_runtime-14.28 | 1.4 MB    | ############################################################################################### | 100%
toolz-0.10.0         | 46 KB     | ############################################################################################### | 100%
python-3.7.9         | 17.9 MB   | ############################################################################################### | 100%
protobuf-3.14.0      | 261 KB    | ############################################################################################### | 100%
cryptography-3.3.1   | 594 KB    | ############################################################################################### | 100%
cffi-1.14.4          | 226 KB    | ############################################################################################### | 100%
future-0.17.1        | 633 KB    | ############################################################################################### | 100%
absl-py-0.8.1        | 158 KB    | ############################################################################################### | 100%
win_inet_pton-1.1.0  | 8 KB      | ############################################################################################### | 100%
pyopenssl-19.1.0     | 83 KB     | ############################################################################################### | 100%
zlib-1.2.11          | 126 KB    | ############################################################################################### | 100%
pysocks-1.7.1        | 27 KB     | ############################################################################################### | 100%
blas-1.0             | 1 KB      | ############################################################################################### | 100%
certifi-2020.4.5.1   | 150 KB    | ############################################################################################### | 100%
libprotobuf-3.14.0   | 2.3 MB    | ############################################################################################### | 100%
numpy-1.19.5         | 4.8 MB    | ############################################################################################### | 100%
setuptools-46.1.3    | 528 KB    | ############################################################################################### | 100%
chardet-3.0.4        | 184 KB    | ############################################################################################### | 100%
openssl-1.1.1i       | 5.8 MB    | ############################################################################################### | 100%
markdown-3.2.1       | 61 KB     | ############################################################################################### | 100%
pycparser-2.20       | 89 KB     | ############################################################################################### | 100%
python_abi-3.7       | 4 KB      | ############################################################################################### | 100%
sqlite-3.34.0        | 1.2 MB    | ############################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\Users\\sslee\\anaconda3\\envs\\mdvc\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\sslee\\Desktop\\MDVC\\condaenv.c_r9
ibeq.requirements.txt']
Pip subprocess output:

Pip subprocess error:
ERROR: Invalid requirement: 'cffi=1.14.0=py37h2e261b9_0' (from line 2 of C:\Users\sslee\Desktop\MDVC\condaenv.c_r9ibeq.requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

failed

CondaEnvException: Pip failed


(base) C:\Users\sslee\Desktop\MDVC>conda env create -f conda_env.yml

CondaValueError: prefix already exists: C:\Users\sslee\anaconda3\envs\mdvc

**Comment by sslee8778960** [comment]
Hi I actually i followed the suggestion by conda that changing "=" into "==", the problem got sorted.

However, I encountered this error now. it is very frustrated to simply build the virtual environment and reproduce your work. Any suggestions? I do have a mac, windows, at hand but no linux system.

ERROR: Could not find a version that satisfies the requirement cffi==1.14.0=py37h2e261b9_0 (from -r C:\Users\sslee\Desktop\MDVC\condaenv.p1r1zucz.requirements.txt (line 2)
) (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.4, 0.4.1, 0.4.2, 0.5, 0.6, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.9.0, 0.9.1, 0.9.2, 1.0.0, 1.0.1, 1
.0.2.post2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.2.0.post1, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.7.0, 1.8.2, 1.8.3, 1.9.0, 1.9.1, 1.10.0, 1.11.
0, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.13.0, 1.13.1, 1.13.2, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4)
ERROR: No matching distribution found for cffi==1.14.0=py37h2e261b9_0 (from -r C:\Users\sslee\Desktop\MDVC\condaenv.p1r1zucz.requirements.txt (line 2))

failed

CondaEnvException: Pip failed

**Comment by sslee8778960** [comment]
> Are you trying to install it on Windows?

Yes I am trying to install it on Windows. Thanks!

**Comment by v-iashin** [comment]
I am sorry. We do not support windows. 

Luckily, we have all requirements listed with versions. So, it should be easy to replicate the environment. The last resort solution would be to create a Docker and try it from there.

**Comment by sslee8778960** [comment]
> I am sorry. We do not support windows.
> 
> Luckily, we have all requirements listed with versions. So, it should be easy to replicate the environment. The last resort solution would be to create a Docker and try it from there.

Thank you very much for the reply. So the original method is supported by Linux? Thanks again.

**Comment by v-iashin** [comment]
I would say that I tested it on Linux and I haven't tested it on windows. 

Maybe it will also work on windows with a properly set up environment.
