### ISSUE TITLE
ResolvePackageNotFound:

### ISSUE THREAD

**Issue by taruntiwarihp** [v-iashin/MDVC#21]
PS D:\Python Pro\Other Project\MDVC> conda env create -f conda_env.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - h5py==2.8.0=py37h989c5e5_3
  - openjdk==11.0.1=h516909a_1016
  - protobuf==3.11.4=py37h3340039_1
  - spacy==2.0.12=py37h962f231_0
  - cffi==1.14.0=py37h2e261b9_0
  - thinc==6.10.3=py37h962f231_0
  - libedit==3.1.20181209=hc058e9b_0
  - readline==8.0=h7b6447c_0
  - regex==2018.07.11=py37h14c3975_0
  - pytorch==1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - libprotobuf==3.11.4=h8b12597_0
  - mkl_fft==1.0.15=py37ha843d7b_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - pandas==0.24.2=py37he6710b0_0
  - torchvision==0.3.0=py37_cu10.0.130_1
  - pillow==7.1.2=py37hb39fc2d_0
  - ujson==2.0.3=py37he6710b0_0
  - zstd==1.3.7=h0b5b093_0
  - libpng==1.6.37=hbc83047_0
  - cryptography==2.8=py37h1ba5d50_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - cymem==1.31.2=py37h6bb024c_0
  - freetype==2.9.1=h8a8886c_1
  - zlib==1.2.11=h7b6447c_3
  - ninja==1.9.0=py37hfd86e86_0
  - cytoolz==0.9.0.1=py37h14c3975_1
  - sqlite==3.31.1=h62c20be_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - hdf5==1.10.2=hba1933b_1
  - libtiff==4.1.0=h2733197_0
  - numpy==1.15.4=py37h7e9f1db_0
  - mkl-service==2.3.0=py37he904b0f_0
  - msgpack-python==0.5.6=py37h6bb024c_1
  - ncurses==6.2=he6710b0_1
  - tk==8.6.8=hbc83047_0
  - wrapt==1.10.11=py37h14c3975_2
  - libffi==3.2.1=hd88cf55_4
  - xz==5.2.5=h7b6447c_0
  - jpeg==9b=h024ee3a_2
  - openssl==1.1.1g=h516909a_0
  - mkl_random==1.1.0=py37hd6b4f25_0
  - murmurhash==0.28.0=py37hf484d3e_0
  - python==3.7.7=hcf32534_0_cpython
  - libgcc-ng==9.1.0=hdf63c60_0
  - numpy-base==1.15.4=py37hde5b4d6_0
  - preshed==1.0.1=py37he6710b0_0

**Comment by v-iashin** [comment]
Windows is not supported

**Comment by taruntiwarihp** [comment]
Then How can i run this on windows, any idea

**Comment by taruntiwarihp** [comment]
I tried in mac and still getting same error

**Comment by v-iashin** [comment]
Ok, sorry, I meant only Linux is supported

**Comment by taruntiwarihp** [comment]
Thanks man, Its working on Ubuntu. your project is Awesome, Great work man!
