### ISSUE TITLE
I have two Issues - 1. I want to run this without GPU (i don't have GPU in Ubuntu)

### ISSUE THREAD

**Issue by taruntiwarihp** [v-iashin/MDVC#22]
(mdvc) tarun@tarun-VirtualBox:~/Downloads/MDVC$ python main.py --device_ids 1
log_path: ./log/0601100925
model_checkpoint_path: ./log/0601100925
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCGeneral.cpp line=50 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "main.py", line 572, in <module>
    main(cfg)
  File "main.py", line 177, in main
    torch.cuda.set_device(cfg.device_ids[0])
  File "/home/tarun/miniconda3/envs/mdvc/lib/python3.7/site-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/tarun/miniconda3/envs/mdvc/lib/python3.7/site-packages/torch/cuda/__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCGeneral.cpp:50

**Comment by taruntiwarihp** [comment]
2 - I want to test (run time) code with input using the camera itself (visual and audio) 
  -> can you explain how can I get input from the camera or OpenCV, also share some code related to it

**Comment by v-iashin** [comment]
1. The code is designed for GPU use only. If you want to run it on CPU, I suggest asking the community to help you or try to adapt it yourself.
2. I don't have any ready-to-use code which you request and I am occupied with other stuff at the moment. You have Google to help you with this.

**Comment by taruntiwarihp** [comment]
Thanks for your help brother !
