### ISSUE TITLE
Bi-SST implementation

### ISSUE THREAD

**Issue by amanchadha** [v-iashin/MDVC#3]
Hello again!

From the paper:
> Firstly, we obtain the temporal event locations. For this task, we employ the Bidirectional Single-Stream Temporal action proposals network (Bi-SST) proposed in [48]

Per [48], a Bi-SST goes through a forward and backward pass and then fuses the results with a fusion operation (typically multiplication). In "models/transformer.py", can you please point me to where this is implemented? Thanks!

**Comment by v-iashin** [comment]
Hi!
Please see the response to Issue #2.
