### ISSUE TITLE
Tool to draw block diagrams

### ISSUE THREAD

**Issue by amanchadha** [v-iashin/MDVC#5]
Hi Vladimir,

Just curious about what tool was used to draw the following diagrams:

1. From the MDVC paper:

![image](https://user-images.githubusercontent.com/20895241/82550258-13f92380-9b13-11ea-91e0-dd09e4c10a19.png)

===

2. All the block-diagrams here: https://v-iashin.github.io/bmt.html

![image](https://user-images.githubusercontent.com/20895241/82550268-1b203180-9b13-11ea-8db1-39757da5ad44.png)

![image](https://user-images.githubusercontent.com/20895241/82550292-22dfd600-9b13-11ea-9c18-7d13aab36332.png)

Thanks for the support!

**Comment by v-iashin** [comment]
Hi,
I found diagrams.net (aka. draw.io) to be a terrific app to do these. It is free and open-sourced.
