### ISSUE TITLE
Error video_stack_rgb and video_stack_flow all is None

### ISSUE THREAD

**Issue by haoxiaopeng** [v-iashin/MDVC#8]
video_stack_rgb = feat_h5_video.get(f'{video_id}/i3d_features/rgb')
video_stack_flow = feat_h5_video.get(f'{video_id}/i3d_features/flow')
video_stack_rgb and video_stack_flow all is None
video_id = 'v_QOlSCBRmfWY'
h5='sub_activitynet_v1-3.i3d_25fps_stack24step24_2stream.hdf5'

**Comment by v-iashin** [comment]
Hi. Thanks for your interest in our work. 

I don't understand the problem you are facing. Let's start with the code which might reproduce your error. I assume you do something like this.

```
$ conda activate mdvc
$ python
```
and you run there:
```python
import h5py
import numpy as np
feat_h5_video = h5py.File('./data/sub_activitynet_v1-3.i3d_25fps_stack24step24_2stream.hdf5', 'r')
video_stack_rgb = feat_h5_video.get('v_QOlSCBRmfWY/i3d_features/rgb')
video_stack_flow = feat_h5_video.get('v_QOlSCBRmfWY/i3d_features/flow')
print(np.array(video_stack_rgb).sum())  # 17516.19
print(np.array(video_stack_flow).sum())  # 12495.1045
```

So, I cannot reproduce your error. Please, provide more details or double-check your setup.

**Comment by haoxiaopeng** [comment]
the md5 not equal with you 
4f571fc943cfdf1c833c5fc9a95583e7 sub_activitynet_v1_3.i3d_25fps_stack24step24_2stream.hdf5

I am download again
